### ISSUE TITLE
不同矩阵代码

### ISSUE THREAD

**Issue by barryjim** [chaosgoo/GMatrixSource#1]
你好,看了你的视频很棒,我也做了一个, 设计灯板的时候 没仔细查资料,S形的,做成了Z形 想问问你代码怎么改

**Comment by chaosgoo** [comment]
`matrix = new FastLED_NeoMatrix(leds, 32, 8, NEO_MATRIX_BOTTOM + NEO_MATRIX_LEFT + NEO_MATRIX_ROWS + NEO_MATRIX_ZIGZAG);`
FastLED_NeoMatrix的构造参数可以配置
